### ISSUE TITLE
seq-map on vector that returns a vector?

### ISSUE THREAD

**Issue by Silex** [NicolasPetton/seq.el#10]
Hello,

Why do some function respect the sequence type and some other convert to list?

Is it because of implementation issues or is it because it's desired? Wouldn't eventually all methods return the same type?

For example, the following surprised me:

``` emacs
(seq-map '1+ [1 2 3 4]) ;; => '(2 3 4 5)
```

Having to `(apply '#vector ...)` all the time annoys me :laughing:

**Comment by NicolasPetton** [comment]
Philippe Vaucher <notifications@github.com> writes:

> Hello,

Hi Phillipe,

> For example, the following surprised me:
>
> ``` emacs
> (-map '1+ [1 2 3 4]) ;; => '(2 3 4 5)
> ```

That seems to be -map for dash.el, but indeed seq.el behaves the same
way here.

I agree that it can be surprising.

**Comment by Silex** [comment]
I see that you reply by email and thus miss the edits I did (I edited it to be `seq-map`).

Anyway, what about the questions? Is it because of implementation issues or is it because it's desired? Shouldn't theoretically all methods return the same type as passed?

**Comment by NicolasPetton** [comment]
Philippe Vaucher <notifications@github.com> writes:

> I see that you reply by email and thus miss the edits I did (I edited
> it to be `seq-map`).

Ah, ok :)

> Anyway, what about the questions? Is it because of implementation
> issues or is it because it's desired? Shouldn't theoretically all
> methods return the same type as passed?

When implementing seq-map, I didn't mind returning a list from another
seq type, as the implementation as much easier that way.

I do understand that it can be surprising though, so I would agree to
change that behavior.

**Comment by Silex** [comment]
Okay, continuing in #11
