### ISSUE TITLE
Byte compile warnings about 't' pattern in pcase

### ISSUE THREAD

**Issue by syohex** [NicolasPetton/seq.el#3]
seq.el should use `_` pattern instead of `t` pattern

```
In seq-concatenate:
seq.el:277:6:Warning: Pattern t is deprecated.  Use `_' instead

In seq--make-pcase-bindings:
seq.el:416:25:Warning: Pattern t is deprecated.  Use `_' instead

In seq--make-bindings:
seq.el:450:25:Warning: Pattern t is deprecated.  Use `_' instead
```

**Comment by NicolasPetton** [comment]
@syohex Which version of Emacs are you using?

**Comment by syohex** [comment]
GNU Emacs 25.0.50.1. Which is built at 2015/OCT/16.

NOTE: `pcase` can use `_` pattern since Emacs 24.1.

**Comment by NicolasPetton** [comment]
The branch of `seq` in Emacs master uses `_` for pcase. You should not install seq.el from this branch on Emacs 25, it's built-in :-)

**Comment by syohex** [comment]
Oh, thanks for information.
