### ISSUE TITLE
What's the use of seq-into-sequence?

### ISSUE THREAD

**Issue by ghost** [NicolasPetton/seq.el#4]
Hi,

I'm a bit irritated about the function "seq-into-sequence".  Can it be removed, or is it supposed to do something different than "identity"?

In case of streams, the implementation converts into a list.  So, should it better be named `seq-into-list'?

BTW, I would prefer "to" instead of "into".  A matter of taste probably.

Thanks!

**Comment by NicolasPetton** [comment]
As you know, seq can be extended to work with new data types. `seq-into-sequence` is here to ensure you get back a "sequence" object, from any "seq", which could be a stream, or any other seq that you would define yourself.

**Comment by ghost** [comment]
Nicolas Petton notifications@github.com writes:

> As you know, seq can be extended to work with new data
> types. seq-into-sequence is here to ensure you get back a "sequence"
> object, from any "seq", which could be a stream, or any other seq that
> you would define yourself.

Ok, so there are "sequence"s, as we know them from Emacs, and "seq"s,
which are a superset of "sequence"s?  That's confusing, because "seq"
sounds like an abbrev for "sequence" at the same time.

**Comment by NicolasPetton** [comment]
Yes, I know.

 We've been talking about this with Eli, and we decided that all function arguments would be changed from "seq" to "sequence", and that it would be stated more clearly that one can extend seq.el to support new data types.

**Comment by ghost** [comment]
Ok.
