### ISSUE TITLE
Compiler warnings in Emacs 24

### ISSUE THREAD

**Issue by phst** [NicolasPetton/seq.el#6]
There are a couple of compiler warnings in Emacs 24 because of the `pcase-defmacro` definition. You can suppress them by surrounding `(fboundp 'pcase-defmacro)` with `eval-when-compile`: that will make the byte compiler skip the branch entirely.

**Comment by NicolasPetton** [comment]
thank you.  It can be simplified even further, as seq.el 2.x is in Emacs 25, this code can be removed from the 1.x branch.

**Comment by NicolasPetton** [comment]
Fixed in https://github.com/NicolasPetton/seq.el/commit/1349714b20daed2e62a21ebdd5244acc0ccbef0c
