### ISSUE TITLE
recursive load when byte compiling?

### ISSUE THREAD

**Issue by ledbettj** [NicolasPetton/seq.el#8]
Hi,

Apologies if this is not a `seq.el` issue, or if it's a user-error problem :smile:.

I have several packages installed through (m)elpa on Emacs 25.0.50.1 on OS X, several of which require `seq.el` as a dependency.  Just recently, perhaps after a package update, I am now seeing `(error "Recursive load")` when emacs starts:

```
Debugger entered--Lisp error: (error "Recursive load" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/bytecomp.elc" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/cl-generic.elc" 
"/Users/john/.emacs.d/elpa/seq-2.15/seq-25.el" 
"/Users/john/.emacs.d/elpa/seq-2.15/seq.el" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/cl-extra.elc" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/bytecomp.elc" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/cl-generic.elc" 
"/Users/john/.emacs.d/elpa/seq-2.15/seq-25.el"
"/Users/john/.emacs.d/elpa/seq-2.15/seq.el" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/cl-extra.elc" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/bytecomp.elc" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/cl-generic.elc" 
"/Users/john/.emacs.d/elpa/seq-2.15/seq-25.el"
"/Users/john/.emacs.d/elpa/seq-2.15/seq.el" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/cl-extra.elc" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/bytecomp.elc" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/cl-generic.elc" 
"/Users/john/.emacs.d/elpa/seq-2.15/seq-25.el"
"/Users/john/.emacs.d/elpa/seq-2.15/seq.el" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/cl-extra.elc" 
"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/emacs-lisp/bytecomp.elc" 
"/Users/john/.emacs.d/elpa/use-package-20160403.1129/use-package.elc"
 "/Users/john/.emacs.d/init.el"
)
```

[Full error output](https://gist.github.com/ledbettj/0f660f9546f605b0c95b3e7e72613c01)

Any ideas or pointers?

**Comment by NicolasPetton** [comment]
If you change `(require 'cl-lib)` with `(require 'cl-extra)` in `seq-25.el`, does that fix your problem?

**Comment by NicolasPetton** [comment]
Also, which commit of Emacs are you on?

**Comment by ledbettj** [comment]
Thanks for the response. Changing `(require 'cl-lib)` to `c-extra` doesn't seem to help.

I see in `cl-extra.el`:

```
;;; cl-extra.el --- Common Lisp features, part 2  -*- lexical-binding: t -*-
;; ...
(require 'cl-lib)
(require 'seq)
```

Which I assume is causing the same problem.

`emacs-version` says:

> GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.3.0, NS appkit-1347.57 Version 10.10.3 (Build 14D136)) of 2015-04-27 on nix.local

Which looks pretty old.  I don't see a `14D136` commit in the repo, and `emacs-repository-version` is `nil`. If you think it might make a difference, I can try with a newer build.

**Comment by ledbettj** [comment]
I reinstalled emacs (`brew install emacs --devel --with-cocoa`) and got:

> GNU Emacs 25.0.92.1 (x86_64-apple-darwin15.4.0, NS appkit-1404.46 Version 10.11.4 (Build 15E65)) of 2016-04-04

And the issue is no longer present -- Thanks for the help troubleshooting!

**Comment by NicolasPetton** [comment]
great!
